from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from . models import Task, UserProfile, Category
from . forms import TaskForm, UserProfileForm
from datetime import date
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404


#   Showing Task list Main things
@login_required
def taskList(request):
    tasks = Task.objects.filter(user = request.user)
    categories = Category.objects.all()
    statuses = ["Complete", "Overdue", "Due Today", "Upcoming", "No Deadline"]


    # --- Search ---
    query = request.GET.get('search', '')    # ?search= . . .
    if query:
        tasks = tasks.filter(title__icontains = query)    # Case-insensitive search in title

    # --- Status Filter ---
    filter_status = request.GET.get('status')
    today = date.today()
    if filter_status:
        if filter_status == 'Complete':
            tasks = tasks.filter(complete=True)
        elif filter_status == 'Overdue':
            tasks = tasks.filter(complete=False, due_date__lt=today)
        elif filter_status == 'Due Today':
            tasks = tasks.filter(complete=False, due_date=today)
        elif filter_status == 'Upcoming':
            tasks = tasks.filter(
                complete=False,
                due_date__gt=today,
                due_date__isnull=False,
                )
        elif filter_status == 'No Deadline':
            tasks = tasks.filter(complete=False, due_date__isnull=True)

    # ---Category Filter--- 
    filter_category = request.GET.get('category')
    if filter_category:
        tasks = tasks.filter(category__id=filter_category)

    context = {
        'taskss': tasks,
        'search_queryy': query,
        'statuses': statuses,
        'filter_statuss': filter_status,
        'categories': categories,
        'filter_category': filter_category,
        }
    return render(request, "ct_todo/task_list.html", context)


# Login page is already generated by Django so you dont have to create its view or form
# not even like registeration form we just need to inject it in html template thats it '''
# Create your user
def registerPage(request):
    if request.user.is_authenticated:               # Checks if user is logged in? 
        return redirect('tasks')
    
    form = UserCreationForm()                       # Storing empty form in this var 

    if request.method == 'POST':
        form = UserCreationForm(request.POST)       # Gets data from html form if form was filled
        if form.is_valid():                         # checks if form is filled properly without mistake
            form.save()                             # Save data in DB that it gets from 'form' var
            return redirect('login')
        
    context = {'formm': form}
    return render(request, 'ct_todo/register.html', context)



# Main thing TASK adding things haha
@login_required
def createTask(request):
    form = TaskForm()

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)          # Create object but don't save
            task.user = request.user                # Set current user as the owner
            task.save()
            return redirect('tasks')
        
    context = {'tform': form}
    return render(request, 'ct_todo/task_form.html', context)




# Updating the Tasks that we added hehe
@login_required
def updateTask(request, pk):
    task = get_object_or_404(Task, id=pk, user=request.user)
    form = TaskForm(instance=task)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save() 
            return redirect('tasks')
    else:
        form = TaskForm(instance=task)
    
    context = {'tform': form}
    return render(request, 'ct_todo/task_form.html', context)




# Avadakedvraing(Delete) the rebeling tasks
@login_required
def deleteTask(request, pk):
    task = Task.objects.get(id=pk, user=request.user)

    if request.method == 'POST':
        task.delete()
        return redirect('tasks')
    
    context = {'dtask': task}
    return render(request, 'ct_todo/delete_confirm.html', context)



# Toggle Complete Task btn
@login_required
def toggle_complete(request, pk):
    task = get_object_or_404(Task, id=pk, user=request.user)
    task.complete = not task.complete   
    task.save()

    return redirect ('tasks')



# User Profile System
@login_required
def profile_view(request):
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile.objects.create(user=request.user)

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('tasks')

    else:
        form = UserProfileForm(instance=profile)


    return render(request, 'ct_todo/user_profile.html', {'form': form, 'profile': profile})



# This is our about-us section
def about_us(request):
    return render(request, 'ct_todo/about_section.html')